--[[
Pie skins unlocked by default should be placed in this folder.

Conditional pie skins (like Badge skins) should be placed in `ServerStorage` > `PieHikingServerStorage` > `PieSkins`.


----- Credits for pie skins -----

- Pumpkin Pi mesh texture from Roblox's Pumpkin Pi gear (asset id 16986805)
- Cherry Pie mesh texture from Roblox's Cherry Pie gear (asset id 40493590)
- Ten-Mou, Moon, Eye, Stealth, and Rhubarb Pie textures from VerticalAscent's Frozen Soul / Dream Game
- Heart Pie texture from me
]]
