--[[
How to setup Heart Pie's Container Scripts:


Manually:

1. Put things inside "ReplicatedStorage" folder into the "ReplicatedStorage" container service.

2. Put things inside "ServerScriptService" folder into the "ServerScriptService" container service.
--- Make sure the script "PieHikingServer" is enabled.

3. Put things inside "StartPlayerScripts" folder into the "StarterPlayerScripts" container object, located under the "StarterPlayer" service.
--- Make sure the script "CSCPieAmmo" under CSCPieActor is enabled.
--- Make sure the scripts "ClientPieAmmo" and "ServerPieAmmo" under PieMotionActor are enabled.

4. Put things inside "ServerStorage" folder into the "ServerStorage" container service.

5. Delete the "ContainerScripts" folder.


Automatically:

1. Select the Heart Pie tool.

2. Copy the code inside ContainerSetUp.

3. Paste it in the command bar & run.

]]
