--[[
How to setup Heart Pie's Container Scripts:

1. Put things inside "ReplicatedStorage" folder into the "ReplicatedStorage" container service.

2. Put things inside "ServerScriptService" folder into the "ServerScriptService" container service.
--- Make sure the script "PieHikingServer" is enabled.

3. Put things inside "StarterGui" folder into the "StarterGui" container service.

4. Put things inside "StartPlayerScripts" folder into the "StarterPlayerScripts" container object, located under the "StarterPlayer" service.
--- Make sure the script "CSCPieAmmo" under CSCPieActor is enabled.
--- Make sure the scripts "ClientPieAmmo" and "ServerPieAmmo" under PieMotionActor are enabled.
]]
