[package]
name = "mariochao/heart-pie"
description = "A complete revamp of the classic pie hiking gear."

version = "2.0.0"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/MarioChao/HeartPie"

private = true

[dependencies]
BadgeUtil = "mariochao/badge-util@0.0.2"
BelovedRemote = "mariochao/beloved-remote@0.0.2"
